//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int userId { get; set; }
        public string employeeName { get; set; }
        public string phoneNumber { get; set; }
        public string role { get; set; }
        public int salary { get; set; }
    }
}
